title:              Clean Blog
email:              your-email@example.com
description:        A Blog Theme by Start Bootstrap
author:             Chapati Mystery
baseurl:            "/chapati"
url:                ""

# Social Profiles
twitter_username:   ChapatiMystery
github_username:    mananahmed
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
